name: Deploy to Render
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Trigger Render deploy (via Deploy Hook)
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
